### ISSUE TITLE
Unable to show Connections tab

### ISSUE THREAD

**Issue by Ogglord** [hudra0/qosmate#19]
I'm running **release 23.05.5 r24106-10cc5fcd00** on a Flint 2 MT6000, QoSMate **v0.5.35** (latest as of today). This was the first package I added after a factory reset. (except for `luci-theme-openwrt-2020` and `auc`) 

The traffic shaping is working excellent. Except when I press Connections tab the following error shows
```
RPC call to luci.qosmate/getConntrackDSCP failed with error -32000: Object not found
  at ClassConstructor.handleCallReply (http://192.168.1.1/luci-static/resources/rpc.js?v=git-24.264.56413-c7a3562:11:3)
```

**Comment by Ogglord** [comment]
ubus call system board => https://pastebin.com/raw/jr9FxmV0

/etc/init.d/qosmate check_version && /etc/init.d/qosmate status => https://pastebin.com/raw/wwtnQAGL

cat /etc/config/qosmate =>  https://pastebin.com/raw/ALPXimDY

**Comment by hudra0** [comment]
Output looks good at first glance. Have you tried clearing your browser cache/restart your router?

**Comment by Ogglord** [comment]
Thanks, however I switched to a custom snapshot Openwrt build (Pesa's). I unfortunately never got the chance to try a reboot or cache clear. I suggest we close this until further notice.
