### ISSUE TITLE
TCP MSS clamping

### ISSUE THREAD

**Issue by dim-geo** [hudra0/qosmate#3]
Hi, in the iptables of Simplehfsc, there was TCP MSS clamping.
Maybe you can add it back in the nftables version.

**Comment by hudra0** [comment]
Hey, MSS clamping was added more than a week ago...

64287e824a13e6079dfdbaed674781001b7f3b0b

It's only active when your up or download is below 3000 kbit/s

and you can change the MSS manually via the UI (advanced tab) or via config
