### ISSUE TITLE
DNS name based classification

### ISSUE THREAD

**Issue by pcislocked** [hudra0/qosmate#30]
Hi, switching from qosify. Over there we can do stuff like this;

`dns:*download.epicgames*      bulk (CS1)`
`dns:*download2.epicgames*     bulk`
`dns:*download3.epicgames*     bulk`
`dns:*download4.epicgames*     bulk`
`dns:*epicgames-download1*     bulk`

(not sure if it worked good or not by the way)

but i dont see the option here

![image](https://github.com/user-attachments/assets/f96d4d63-9855-4970-a945-c834c7abce4e)

I specifically mean being able to classify destination IPs based on either by ipsets (which can be filled by dnsmasq for some domains) or by directly indicating domains themselves

am i missing something, or can we implement it if its easy pls thanks

**Comment by brada4** [comment]
You can write custom rules with nftsets.

**Comment by hudra0** [comment]
There isn't a direct function for this, but as @brada4  mentioned, you can create rules and nftsets (even through the Custom Rules UI tab).

Additionally, such a rule shouldn't be necessary (at least not with your example) with qosmate, as we automatically downgrade TCP traffic that has transferred more than 10 seconds' worth of packets to CS1, which is the lowest priority (bulk).

**Comment by pcislocked** [comment]
> There isn't a direct function for this, but as @brada4  mentioned, you can create rules and nftsets (even through the Custom Rules UI tab).
> 
> Additionally, such a rule shouldn't be necessary (at least not with your example) with qosmate, as we automatically downgrade TCP traffic that has transferred more than 10 seconds' worth of packets to CS1, which is the lowest priority (bulk).

didn't know that function, good to know

will check it out, thanks 🙏
