### ISSUE TITLE
Any chance for variable connection? (E.g. 4G, 5G, Starlink, etc.)

### ISSUE THREAD

**Issue by apa-u** [hudra0/qosmate#4]
Hi, I’m quite interested in QosMate. Would there be a chance that you’ll be able to implement or enable this setup for those who have variable connection. Especially for users who use 5G home internet? Thank you so much!

**Comment by hudra0** [comment]
Something like cake-autorate could theoretically be implemented, but it would likely take some time to accomplish.

https://github.com/lynxthecat/cake-autorate

**Comment by apa-u** [comment]
Thank you so much @hudra0 ! looking forward to it.
